/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define EEPROM_ADDR		0xA0

#define I2C_TASK_TIME	1000

static software_timer_t i2c_timer;

static uint8_t data_w[8] = {0x31,0x32,0x33,0x34,0x25,0x26,0x27,0x28};
static uint8_t data_r[8] = {0};

int main(void)
{
	rcc_init();
	i2c_init();

	i2c_reg_write_dma(EEPROM_ADDR, 0x00, data_w, sizeof(data_w));
	LL_mDelay(100);

	software_timer_task_init(&i2c_timer, I2C_TASK_TIME);

	while (1)
	{
		  if((software_timer_get_ms_tick() - i2c_timer.ms_tick) >= i2c_timer.task_time)
		  {
			  	i2c_timer.ms_tick = software_timer_get_ms_tick();
				i2c_reg_read(EEPROM_ADDR, 0x00, data_r, sizeof(data_r));
		  }
	}
}

void rcc_init(void)
{
	LL_FLASH_SetLatency(LL_FLASH_LATENCY_2);

	LL_RCC_HSI_Enable();
	while(LL_RCC_HSI_IsReady() != 1)
		;

	LL_RCC_PLL_ConfigDomain_SYS(LL_RCC_PLLSOURCE_HSI, LL_RCC_PLLM_DIV_1, 8, LL_RCC_PLLR_DIV_2);

	LL_RCC_PLL_Enable();
	while(LL_RCC_PLL_IsReady() != 1)
		;

	LL_RCC_PLL_EnableDomain_SYS();

	LL_RCC_SetAHBPrescaler(LL_RCC_SYSCLK_DIV_1);
	LL_RCC_SetAPB1Prescaler(LL_RCC_APB1_DIV_1);

	LL_RCC_SetSysClkSource(LL_RCC_SYS_CLKSOURCE_PLL);
	while(LL_RCC_GetSysClkSource() != LL_RCC_SYS_CLKSOURCE_STATUS_PLL)
		;

	LL_SetSystemCoreClock(64000000);
	LL_Init1msTick(64000000);
	LL_SYSTICK_EnableIT();
}
